---
pool: gopi
  
trigger: 
    - master 
    
resources:
  repositories: 
    - repository: azuredevopsparamteres 
      endpoint: github_id
      ref: refs/heads/main
      name: Nagaraju11111/learninggit
      type: github    
  
stages:
  - template: azuredevops/maventemplate.yaml@azuredevopsparamteres 
    parameters:
      goal: 'package' 
      javaversion: '1.8' 
      javadirectory: /usr/lib/jvm/java-8-openjdk-amd64/